version: '3.9'
services:
  mongo:
    image: mongo:4.4.3-bionic
    container_name: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ~/data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      TZ: ${TIMEZONE}
    restart: always
    networks:
      - eca_net
  api:
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: sh scripts/dev.sh
    depends_on:
      - mongo
    networks:
      - eca_net
networks:
  eca_net:
    name: eca_net
